### ISSUE TITLE
format fixes 06/02

### ISSUE THREAD

**Issue by jueyang** [jueyang/almostatlas#4]
- [x] Index page typos
- [x] In Dating Dysphoria
- [x] How to Drain a Brachial Artery
- [x] Creation Myth 18
- Men & Women of a Town
  - [x] dialogue line break
  - [x]  indentation of paragraphs but the first
- [x] Self on the First Date
- [x] Species Dysphoria
- The Tap Water Tastes Like Chlorine
  - [x] "Can this bit be moved to read as a byline? It's a reference to the translated author's name, and the translators's names? You can go ahead and replace what's currently in the byline ("Julia Cohen"), as her name appears in this blurb." Not sure if I got that.
  - [x] format
- [x] Love Poem Ending on a Line...

**Comment by jueyang** [comment]
@paperstarships Hello. Running into  trouble with the indentations with Men and Women in Town. Here's [an attempt](https://github.com/jueyang/almostatlas/blob/gh-pages/css/site.scss#L125).

Tried to reset the first paragraph by doing:

```
&.prose.present p:first-child {
  text-indent:0;
}
```

but the pseudo-element ain't working. 

Can I borrow some wisdom?

**Comment by paperstarships** [comment]
@jueyang Looking at the site now, I'm not sure what you're trying to do-- are you trying to make it so that only the first paragraph has the indent? It looks like you commented out the indents for now, so I'm just making sure I understand!

**Comment by jueyang** [comment]
all fixed but https://github.com/jueyang/almostatlas/issues/6
